plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

dependencies {
    // JUnit 5 API und Engine für Tests
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.0'

    // AssertJ für flüssige und ausdrucksstarke Assertions
    testImplementation 'org.assertj:assertj-core:3.24.2'
}

test {
    useJUnitPlatform()
}
application{
    mainClass = 'Main'  // Dies gibt an, dass Main die Hauptklasse ist

}
